# Generated by Django 4.0.2 on 2022-02-06 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_goods', '0002_alter_item_options_alter_item_code_alter_item_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='DRF_Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('weight', models.FloatField(verbose_name='Масса')),
            ],
        ),
    ]
