# Generated by Django 3.2.9 on 2021-11-14 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advertisements', '0005_alter_advertisement_status'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='advertisement',
            table='advertisements',
        ),
    ]
